[tool.poetry]
name = "poetry add pandas"
version = "2.2.3"
description = "Pandas"
authors = ["None"]
license = "None"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
